import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { GraphQLClient, gql } from 'graphql-request';
import BlogCard from '../components/BlogCard';

const graphcms = new GraphQLClient(
  'https://api-eu-central-1-shared-euc1-02.hygraph.com/v2/clcs6pcji127t01t94ow29bx4/master'
);

const QUERY = gql`
  {
    posts {
      id
      title
      datePublished
      slug
      content {
        html
      }
      author {
        name
        avatar {
          url
        }
      }
      coverPhoto {
        publishedAt
        publishedBy {
          id
        }
        url
      }
    }
  }
`;

export async function getStaticProps() {
  const { posts } = await graphcms.request(QUERY);
  return {
    props: {
      posts,
    },
    revalidate: 10,
  };
}

export default function Home({ posts }) {
  return (
    <>
      <Head>
        <title>Blog | Jovic Miroslav</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="logoMJ.png" />
        {/* <link rel="shortcut icon" href="logoMJ.png" type="image/x-icon" /> */}
      </Head>

      <main className={styles.main}>
        {posts.map((post) => (
          <BlogCard
            key={post.id}
            {...post}
          // title={post.title}
          // author={post.author}
          // coverPhoto={post.coverPhoto}
          // key={post.id}
          // datePublished={post.datePublished}
          // slug={post.slug}
          />
        ))}
      </main>
    </>
  );
}
